### ISSUE TITLE
conv2d(): argument 'input' (position 1) must be Tensor, not tuple

### ISSUE THREAD

**Issue by victoic** [robintzeng/mask-rcnn-Pytorch#1]
Hello. I'm training over COCO dataset with the mask rcnn model you provide. However, when the batch is loaded I noticed the code sends to the model a list of images (not a Tensor), presumably because the loaded images have different resolutions, but this does not run as it returns the error `conv2d(): argument 'input' (position 1) must be Tensor, not tuple`.

How are you avoiding this error?

**Comment by robintzeng** [comment]
Do you follow the instruction and run the correct train_coco.py and the .sh file to prepare the coco dataset ? 
I didn't face this problem before and the error message show that you may use the wrong data path.
